<?php return array(
    'root' => array(
        'name' => 'tobid/bienesraices',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => null,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'intervention/gif' => array(
            'pretty_version' => '4.1.0',
            'version' => '4.1.0.0',
            'reference' => '3a2b5f8a8856e8877cdab5c47e51aab2d4cb23a3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../intervention/gif',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'intervention/image' => array(
            'pretty_version' => '3.6.5',
            'version' => '3.6.5.0',
            'reference' => 'd428433aa74836ab75e8d4a5241628bebb7f4077',
            'type' => 'library',
            'install_path' => __DIR__ . '/../intervention/image',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tobid/bienesraices' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => null,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
